database:
  driverClass: org.h2.Driver
  user: sa
  password:
  url: jdbc:h2:mem:sample

  properties:
    charSet: UTF-8
    hibernate.dialect: org.hibernate.dialect.H2Dialect
    hibernate.hbm2ddl.auto: create

server:
    applicationConnectors:
      - type: http
        port: 8080
    adminConnectors:
      - type: http
        port: 8081