version: '3'
services:
  4finance-homework:
    build:
      context: .
    tty: true
    container_name: 4finance-homework
    ports:
      - 8080:8080
    depends_on:
      - mypostgres
  mypostgres:
    image: postgres
    ports:
    - 5432:5432
    environment:
    - POSTGRES_PASSWORD=password
    - POSTGRES_USER=postgres
    - POSTGRES_DB=homework

